New Password challenge fix (#13)
* New Password challenge fix

New password Challenge requires parameters initiate_auth request. Without them we get:
```
botocore.errorfactory.NotAuthorizedException: An error occurred (NotAuthorizedException) when calling the RespondToAuthChallenge operation: Unable to verify secret hash for client <cleint_id>
```

* black lint

* flake8 lint